# Generated by Django 5.2.7 on 2025-11-09 21:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_status_alter_category_icon_providerdashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProviderDashboard',
            new_name='OwnerDashboard',
        ),
    ]
