# Generated by Django 5.2.7 on 2025-11-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerDashboard',
        ),
    ]
