# Generated by Django 5.2.7 on 2025-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_delete_ownerdashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='service_profile/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='logo_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='service_logos/'),
        ),
    ]
