# Generated by Django 5.2.7 on 2025-12-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_adpackage_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='visits_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
