# Generated by Django 5.2.7 on 2025-12-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_service_likes_count_service_visits_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='title',
        ),
    ]
