# Generated by Django 5.2.7 on 2025-12-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_ad_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='delete_allowed',
        ),
    ]
