# Generated by Django 5.2.7 on 2026-01-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_service_latitude_service_longitude'),
        ('services', '0017_remove_service_email_favorite'),
    ]

    operations = [
    ]
