# Generated by Django 5.2.7 on 2026-01-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_merge_20260112_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='likes_count',
        ),
    ]
