# Generated by Django 5.2.7 on 2026-01-16 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_remove_service_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bounds_sw_lat', models.FloatField()),
                ('bounds_sw_lon', models.FloatField()),
                ('bounds_ne_lat', models.FloatField()),
                ('bounds_ne_lon', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='directorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.directorate'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bounds_sw_lat', models.FloatField()),
                ('bounds_sw_lon', models.FloatField()),
                ('bounds_ne_lat', models.FloatField()),
                ('bounds_ne_lon', models.FloatField()),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.directorate')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.street'),
        ),
    ]
