# Generated by Django 5.2.7 on 2026-01-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_directorate_service_directorate_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='directorate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='directorate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='street',
        ),
        migrations.DeleteModel(
            name='Directorate',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
