# Generated by Django 5.2.7 on 2026-01-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_street_directorate_remove_service_directorate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم المديرية')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='directorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.directorate'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الشارع')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='services.directorate')),
            ],
            options={
                'unique_together': {('name', 'directorate')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.street'),
        ),
    ]
