# Generated by Django 5.2.7 on 2026-01-20 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_directorate_service_directorate_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='اسم البنك')),
                ('account_name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('account_number', models.CharField(max_length=100, verbose_name='رقم الحساب / المحفظة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='ad_payment_receipts/', verbose_name='صورة سند الدفع')),
                ('sender_name', models.CharField(max_length=100, verbose_name='اسم المرسل')),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم المرسل')),
                ('amount', models.PositiveIntegerField(verbose_name='المبلغ المدفوع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='services.ad')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='services.paymentaccount')),
            ],
        ),
    ]
