# Generated by Django 5.2.7 on 2026-01-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_paymentaccount_adpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الحساب'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب / المحفظة'),
        ),
    ]
