# Generated by Django 5.2.7 on 2026-01-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_alter_paymentaccount_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='adpayment',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='adpayment',
            name='payment_account',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='notes',
        ),
    ]
