# Generated by Django 5.2.7 on 2026-01-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_remove_adpayment_amount_remove_adpayment_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adpayment',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='adpayment',
            name='sender_phone',
        ),
    ]
