# Generated by Django 5.2.7 on 2026-01-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_remove_adpayment_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='receipt_image',
            field=models.ImageField(default='map.png', upload_to='ad_payment_receipts/', verbose_name='صورة سند الدفع'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdPayment',
        ),
    ]
