# Generated by Django 5.2.7 on 2025-10-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='777777777', max_length=9),
            preserve_default=False,
        ),
    ]
