# Generated by Django 5.2.7 on 2025-10-16 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يبدأ بـ 7 ويتكون من 9 أرقام', regex='^7\\d{8}$')]),
        ),
    ]
