# Generated by Django 5.2.7 on 2025-10-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'مشرف'), ('user', 'مستخدم عادي'), ('provider', 'صاحب خدمة')], default='user', max_length=10),
        ),
    ]
