# Generated by Django 5.2.7 on 2025-10-18 19:41

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=users.models.default_profile_image, null=True, upload_to='user_profile/'),
        ),
    ]
