# Generated by Django 5.2.7 on 2025-10-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active_user',
            field=models.BooleanField(default=True),
        ),
    ]
