# Generated by Django 5.2.7 on 2025-10-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_is_active_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
