# Generated by Django 5.2.7 on 2025-10-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_suspended_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active_user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='suspended_at',
        ),
    ]
