# Generated by Django 5.2.7 on 2025-10-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_is_active_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'مشرف'), ('user', 'مستخدم عادي'), ('owner', 'صاحب خدمة')], default='user', max_length=10),
        ),
    ]
