# Generated by Django 5.2.7 on 2025-11-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_service',
            field=models.BooleanField(default=False),
        ),
    ]
