# Generated by Django 5.2.7 on 2025-11-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_has_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_service',
        ),
    ]
