# Generated by Django 5.2.7 on 2025-12-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_review_unique_together_comment_commentimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='review',
        ),
    ]
