# Generated by Django 5.2.7 on 2026-01-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_customuser_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_verified',
        ),
    ]
